CREATE OR REPLACE DATABASE CONNECTORS_DEST_DB;
GRANT CREATE SCHEMA ON DATABASE CONNECTORS_DEST_DB TO APPLICATION SNOWFLAKE_CONNECTOR_FOR_POSTGRESQL;

ALTER SESSION SET AUTOCOMMIT = TRUE;
USE SCHEMA "SNOWFLAKE_CONNECTOR_FOR_POSTGRESQL".PUBLIC;

-- Adding a data source for replication
CALL ADD_DATA_SOURCE('PSQLDVDRENTAL', 'CONNECTORS_DEST_DB');

-- Adding source tables for replication
CALL ADD_TABLES('PSQLDVDRENTAL', 'dvd', ARRAY_CONSTRUCT('city', 'country', 'customer'));

-- Viewing data sources
SELECT * FROM DATA_SOURCES;

-- Viewing the replication state of source tables
SELECT * FROM REPLICATION_STATE;

SELECT count(*) FROM CONNECTORS_DEST_DB."dvd"."customer";